apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: msal-net-proxy-az-file-pv-claim
  namespace: ingress-basic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi