apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: ingress-basic
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/msal/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/msal/index?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-injected-aio,x-injected-name,x-injected-nameidentifier,x-injected-objectidentifier,x-injected-preferred_username,x-injected-tenantid,x-injected-uti"
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - t20.mikerichter.us
    secretName: tls-secret
  rules:
  - host: t20.mikerichter.us
    http:
      paths:
      - backend:
          serviceName: kuard-pod
          servicePort: 8080
        path: /(.*)
      - backend:
          serviceName: ingress-demo
          servicePort: 80
        path: /hello-world-two(/|$)(.*)

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: msal-net-proxy
  namespace: ingress-basic
spec:
  rules:
  - host: t20.mikerichter.us
    http:
      paths:
      - backend:
          serviceName: msal-net-proxy
          servicePort: 80
        path: /msal
  tls:
  - hosts:
    - t20.mikerichter.us
    secretName: tls-secret