apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: msal-net-proxy
  name: msal-net-proxy
  namespace: ingress-basic
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: msal-net-proxy
  template:
    metadata:
      labels:
        k8s-app: msal-net-proxy
    spec:
      containers:
      -  image: richtercloud/msal-net-proxy-opt:latest
         imagePullPolicy: Always
         name: msal-net-proxy
         env:
         -  name: DataProtectionFileLocation
            value: /mnt/dp
         -  name: ForceHttps
            value: "true"
         -  name: AzureAd__Instance
            value: https://login.microsoftonline.com/
         -  name: AzureAd__Domain
            value: microsoft.onmicrosoft.com
         -  name: AzureAd__TenantId
            valueFrom:
              secretKeyRef:
                name: azure-ad-secrets
                key: AzureAd__TenantId
         -  name: AzureAd__ClientId
            valueFrom:
              secretKeyRef:
                name: azure-ad-secrets
                key: AzureAd__ClientId
         -  name: AzureAd__CallbackPath
            value: /msal/signin-oidc
         -  name: AzureAd__SignedOutCallbackPath
            value: /msal/signout-callback-oidc
         -  name: AzureAd__ClientSecret
            valueFrom:
              secretKeyRef:
                name: azure-ad-secrets
                key: AzureAd__ClientSecret
         -  name: Logging__LogLevel__Default
            value: Debug
         -  name: AllowedHosts
            value: "*"
         -  name: RedirectParam
            value: rd
         -  name: ShowLogin
            value: "false"    
         ports:
         - containerPort: 80
           protocol: TCP
         volumeMounts:
         - mountPath: "/mnt/dp"
           name: dpvol
      volumes:
      - name: dpvol
        persistentVolumeClaim:
          claimName: msal-net-proxy-az-file-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: msal-net-proxy
  name: msal-net-proxy
  namespace: ingress-basic
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: msal-net-proxy